# Generated by Django 3.0.3 on 2020-02-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200222_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='my_field',
        ),
    ]
