# Generated by Django 3.0.3 on 2020-02-22 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200223_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='my_field',
            new_name='content',
        ),
    ]
